var v=Object.defineProperty;var S=(t,e,a)=>e in t?v(t,e,{enumerable:!0,configurable:!0,writable:!0,value:a}):t[e]=a;var f=(t,e,a)=>S(t,typeof e!="symbol"?e+"":e,a);import{a as m,S as x,i as d}from"./assets/vendor-C4-ZuMk8.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();m.defaults.baseURL="https://pixabay.com/api/";const E="46451021-7873f1dc2ed25ef257fef9075";async function y({query:t,page:e,perPage:a}){return(await m.get("",{params:{key:E,q:t,page:e,per_page:a,image_type:"photo",orientation:"horizontal",safesearch:"true"}})).data}let C=new x(".photo-card a",{captionDelay:250,captionsData:"alt"});function D(t){t.innerHTML=""}function b(t){return t.map(({webformatURL:e,largeImageURL:a,tags:i,likes:r,views:s,comments:n,downloads:q})=>`
      <div class="photo-card">
        <a href="${a}" class="gallery-item">
          <img src="${e}" alt="${i}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b>${r}</p>
          <p class="info-item"><b>Views</b>${s}</p>
          <p class="info-item"><b>Comments</b>${n}</p>
          <p class="info-item"><b>Downloads</b>${q}</p>
        </div>
      </div>
      `).join("")}function L(t,e){t.insertAdjacentHTML("beforeend",e)}function P(){C.refresh()}const l=class l{constructor(e){this.button=e}disable(){this.button.disabled=!0}enable(){this.button.disabled=!1}hide(){this.button.classList.add(l.HIDDEN_CLASS)}show(){this.button.classList.remove(l.HIDDEN_CLASS)}setLoading(){this.disable(),this.prevText=this.button.textContent,this.button.textContent="Loading images, please wait..."}setNormal(){this.button.textContent=this.prevText,this.enable()}};f(l,"HIDDEN_CLASS","is-hidden");let p=l;const N=document.querySelector("#search-form"),u=document.querySelector(".gallery"),h=document.querySelector(".load-more"),g=document.querySelector(".loader"),c=new p(h),o={page:1,perPage:15,maxPage:1,query:""};N.addEventListener("submit",R);function R(t){t.preventDefault(),o.page=1;const e=t.target.elements.searchQuery.value.trim();if(e===""){d.error({title:"Error",message:"Please enter a search query!",position:"topRight"});return}o.query=e,D(u),$()}async function $(t){g.style.display="inline-block",c.hide();try{const e=await y({query:o.query,page:o.page,perPage:o.perPage});if(e.hits.length===0){d.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}o.maxPage=Math.ceil(e.totalHits/o.perPage);const a=b(e.hits);L(u,a),P(),o.maxPage>o.page&&(c.show(),h.addEventListener("click",w))}catch(e){d.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{g.style.display="none"}}async function w(t){c.setLoading(),o.page+=1;try{const e=await y({query:o.query,page:o.page,perPage:o.perPage}),a=b(e.hits);L(u,a),P();const{height:i}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:(i+16)*2,behavior:"smooth"}),c.setNormal(),o.maxPage===o.page&&(c.hide(),h.removeEventListener("click",w),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){d.error({title:"Error",message:`Something went wrong: ${e.message}`,position:"topRight"})}finally{g.style.display="none"}}
//# sourceMappingURL=index.js.map
